Models/CustomerProducts.cs
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace store1.Models
{
    public class CustomerProducts
    {

        public int Id { get; set; }
        public int CustomerId { get; set; }
        public  virtual Customer  Customer { get; set; }
        public int ProductId { get; set; }
        
        public virtual Products Product { get; set; }

        /*internal object Include(Func<object, object> value)
        {
            throw new NotImplementedException();
        }*/
    }
}

Models/MViews/CustomerProductViewModel.cs
namespace store1.Models.MViews
{
    public class CustomerProductViewModel
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public virtual Customer Customer { get; set; }
        public int ProductId { get; set; }
        
         public virtual Products Product { get; set; }
        public CustomerProductViewModel(int id, int customerId, int productId)
        {
            Id = id;
            CustomerId = customerId;
            ProductId = productId;
        }
        public CustomerProductViewModel()
        {

        }
    }
}

Models/Relations/CustomerProduct.cs
namespace store1.Models.Relations
{
    public class CustomerProduct
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Customer customer { get; set; }
        public int ProductId { get; set; }
        public Products product { get; set; }
    }
}

Controllers/CustomerProductController.cs
using Castle.Core.Resource;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using store1.Data;
using store1.Models;
using store1.Models.MViews;
using System.Linq;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace store1.Controllers
{
    public class CustomerProductController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CustomerProductController(ApplicationDbContext context)
        {
            this._context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var customers = _context.Customer_Products.ToList();
            List<CustomerProductViewModel> cpList = new List<CustomerProductViewModel>();

            if (customers != null)
            {

                foreach (var customerProd in customers)
                {
                    var CPViewModel = new CustomerProductViewModel()//CPViewmodel=CustomerProductViewModel
                    {
                        Id = customerProd.Id,
                        CustomerId = customerProd.CustomerId,
                        ProductId = customerProd.ProductId,
                    };
                    cpList.Add(CPViewModel);
                }
                return View(cpList);
            }
            return View(cpList);

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCustomerProduct(CustomerProductViewModel customerP)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var customerProduct = new CustomerProducts()
                    {
                        Id = customerP.Id,
                        ProductId = customerP.ProductId,
                        CustomerId = customerP.CustomerId,
                    };
                    _context.Customer_Products.Add(customerProduct);
                    _context.SaveChanges();
                    TempData["successMessage"] = "Customer created successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["errorMessage"] = "Model data is not valid";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {

                TempData["errorMessage"] = e.Message;
                return RedirectToAction("Index");
            }

        }
        public IActionResult MPcreate()
        {
            CustomerProducts customerProduct = new CustomerProducts();
            return PartialView("MPcreate", customerProduct);
        }
        //[HttpPost]
        //public IActionResult QuickCreateCustomerProduct(CustomerProducts customerProduct)
        //{
        //    _context.Customer_Products.Add(customerProduct);
        //    _context.SaveChanges();
        //    return RedirectToAction("Index");
        //}    
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            try
            {
                var customer = _context.Customer_Products.SingleOrDefault(x => x.Id == Id);
                if (customer != null)
                {
                    var CustomerprodView = new CustomerProductViewModel()
                    {
                        Id = customer.Id,
                        CustomerId = customer.CustomerId,
                        ProductId = customer.ProductId

                    };
                    return View(CustomerprodView);
                }
                else
                {
                    TempData["errorMessage"] = $"Customer details are not avaliable with Id : {Id}";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["error Message"] = e.Message;
                return RedirectToAction("Index");
            }

        }
        [HttpPost]
        public IActionResult EditCustomerProduct(CustomerProductViewModel model)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    var customer = new CustomerProducts()
                    {
                        Id = model.Id,
                        CustomerId = model.CustomerId,
                        ProductId = model.ProductId,
                    };
                    _context.Customer_Products.Update(customer);
                    _context.SaveChanges();
                    TempData["sucessMessage"] = "customerPrdouct details Updated Successully!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["errorMessage"] = "Model data is invalid";
                    return RedirectToAction("Index"); ;
                }
            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return RedirectToAction("Index"); ;
            }
        }
        public IActionResult QuickEdit(int Id)
        {
            var query=_context.Customer_Products.SingleOrDefault(p=>p.Id == Id);
            if (query != null)
            {
                var CustomerprodView = new CustomerProductViewModel()
                {
                    Id = query.Id,
                    CustomerId = query.CustomerId,
                    ProductId = query.ProductId

                };
                return PartialView("QuickEdit",CustomerprodView);
            }
            else
            {
                TempData["errorMessage"] = $"Customer details are not avaliable with Id : {Id}";
                return RedirectToAction("Index");
            }
            //return PartialView();
        }
        /*public IActionResult QuickShow(int Id)
        {
            var query = _context.Customer_Products.Include(c => c.Customer).Include(p => p.Product).FirstOrDefault(x => x.Id == Id);

            return PartialView("QuickShow",query);
        }*/
        //[HttpGet]
        //public IActionResult Show()
        //{
        //    return View();
        //}
        //        [HttpGet]
        //        public IActionResult ShowTopCustomer(int id) 
        //        {



        //    var query = _context.Customer_Products.SingleOrDefault(x => x.Id == Id);

        //        var result = new TopViewModel()
        //        {
        //            CustomerName = query.Customer.Name,
        //            CustomerType = query.Customer.type,
        //            ProductName = query.Product.Name,
        //            wholesalePrice = query.Product.wholesalePrice,


        //        };

        //    return View(result);


        //}
        [HttpGet]
        public  IActionResult Details (int Id)
        {

            var query = _context.Customer_Products.Include(c => c.Customer).Include(p =>p.Product).FirstOrDefault(x => x.Id==Id);
            return   View(query);
        }

        //else {
        //    var result = new RegularCustomerViewModel()
        //    {
        //        CustomerName = query.Customer.Name,
        //        Customertype = query.Customer.type,
        //        ProductName = query.Product.Name,
        //        price = query.Product.wholesalePrice,


        //    };
        //}
        //return View();

        //[HttpGet]
        //public IActionResult ShowRegularCustomer(int id)
        //{
        //    var customers = _context.Customer_Products.SingleOrDefault(x => x.Id == id);

        //    var result = new RegularCustomerViewModel()
        //    {
        //        CustomerName = customers.Customer.Name,
        //        Customertype = customers.Customer.type,
        //        ProductName = customers.Product.Name,
        //        price = customers.Product.price,


        //    };
        //    return View(result);

        //}
        /*foreach (var customer in Customerquery)
        {
            var model = new RegularCustomerViewModel()//CPViewmodel=CustomerProductViewModel
            {

                CustomerName = customer.CustomerName,
                Customertype = customer.Customertype,
                ProductName=customer.ProductName,
                price = customer.price


            };
            //return View(Customerquery);


        }
        return View(Customerquery);

    }*/
        //[HttpGet]
        //public IActionResult ShowPriceByCustomerType(string type)
        //{//SELECT Customers.name,Products.Name,Products.wholesalePrice from customer_products inner join customers on customer_products.CustomerId=customers.Id inner join products on customer_products.ProductId=products.id;

        //    /*SELECT Customers.name,Customers.type,Products.Name,Products.Price from customer_products inner join customers on customer_products.CustomerId=customers.Id inner join products on customer_products.ProductId=products.id where type="Regular";

        //     *THIS QUERY FOR REGULAR CUSTOMER*/
        //    //  try
        //    //{
        //    //   return View();



        //    else 
        //    {
        //        var regularCustomerquery = _context.Customer_Products
        //        .Join(
        //        _context.Customers,
        //        customerprod => customerprod.CustomerId,
        //        customer => customer.Id
        //        , (customerprod, customer) => new
        //        {
        //            CustomerId = customer.Id,
        //            CustomerName = customer.Name,
        //            CustomerType = customer.type,
        //            productId = customerprod.ProductId


        //        }
        //            )
        //        .Where(customer => customer.CustomerType == "Top")
        //        .Join(_context.Products,

Views/CustomerProduct/Delete.cshtml
@model store1.Models.MViews.CustomerProductViewModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Delete Admin";
    var errorMessage = TempData["errorMessage"]?.ToString();

}
<h3>@ViewData["Title"]</h3>
<br />

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
</head>
<body>
    @if (!string.IsNullOrWhiteSpace(errorMessage))
    {
        <div class="alert alert-danger">
            <strong>Error:</strong>@errorMessage
            <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }


    <form asp-action="DeleteCustomerProduct" method="post">

        <div class="mb-3">
            <label class="form-label">
                Id
            </label>
            <input type="text" class="form-control" asp-for="Id" readonly />
        </div>
        
        <div class="mb-3">
            <label class="form-label">
                CustomerId
            </label>
            <input type="text" class="form-control" asp-for="CustomerId" readonly />

        </div> 
        <div class="mb-3">
            <label class="form-label">
               ProductId
            </label>
            <input type="text" class="form-control" asp-for="ProductId" readonly />

        </div>
        <div>
            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete admin:@Model.Id')">Delete</button>
        </div>
    </form>
</body>
</html>

Views/CustomerProduct/Details.cshtml
@model store1.Models.CustomerProducts
@{
    Layout = "_layout";
}
@Model List<CustomerProductModel>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <style>
        tr{margin :5px}
    </style>
</head>
<body>

    @if (Model != null && Model.Customer.type == "Top")
        {
            <h3 class="h-25">Customer Name</h3>
            <p class="p-1">@Html.DisplayFor(modelitem=>Model.Customer.Name)</p>
            <h3 class="h-25">Customer type</h3>
            <p>@Html.DisplayFor(modelitem=>Model.Customer.type)</p>
    
            
    
       
            
        <br />
        <table class="table table-responsive table-hover ">
            <tr>    
            <th>Product name</th>
                <th>Product Sale price</th>
            </tr>
                <tr>
                    
                        <td>@Html.DisplayFor(product=>Model.Product.Name)</td>
                        <td>@Html.DisplayFor(product=>Model.Product.wholesalePrice)</td>
                    
                </tr>
            
            </table>
        }

        else
        {
            <h3 class="h-25">Customer Name</h3>
            <p class="p-1">@Html.DisplayFor(modelitem=>Model.Customer.Name)</p>
            <h3 class="h-25">Customer type</h3>
            <p>@Html.DisplayFor(modelitem=>Model.Customer.type)</p>
            <br />
            <table class="table table-responsive table-hover ">
            <tr>
                    <th>Product name</th>
                    <th>Product price</th>
            </tr>
                <tr>
                    
                        <td>@Html.DisplayFor(product=>Model.Product.Name)</td>
                        <td>@Html.DisplayFor(product=>Model.Product.wholesalePrice)</td>
                    
                </tr>
            
            </table>
        }
</body>
</html>

Views/CustomerProduct/Edit.cshtml
@model store1.Models.MViews.CustomerProductViewModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Edit Admin";
    var errorMessage = TempData["errorMessage"]?.ToString();
    var successMessage = TempData["successmessage"]?.ToString();
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
</head>
@if (!string.IsNullOrWhiteSpace(errorMessage))
{
    <div class="alert alert-danger">
        <strong>Error! : </strong>@errorMessage
        <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


<form asp-action="EditCustomerProduct" method="post">

    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly />

    </div>
    <div class="mb-3">
        <label class="form-label">CustomerId</label>
        <input type="text" class="form-control" asp-for="CustomerId" />
        <span asp-validation-for="CustomerId" class="text-danger"></span>

    </div>
    <div class="mb-3">
        <label class="form-label">ProductId</label>
        <input type="text" class="form-control" asp-for="ProductId" />
        <span asp-validation-for="ProductId" class="text-danger"></span>

    </div>

    <div class="d-grid">
        <button type="submit" class="btn btn-success">Update</button>
    </div>
</form>

</html>
@section scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/CustomerProduct/Index.cshtml
@using store1.Models;
@using store1.Models.MViews;
@model List<store1.Models.MViews.CustomerProductViewModel>

@{
    ViewData["Title"] = "CustomerIndex";
    var errorMessage = ViewData["errorMessage"]?.ToString();

}
@Model List<CustomerProductModel>

    @if (!string.IsNullOrWhiteSpace(errorMessage))
    {
        <div class="alert alert-danger">
            <strong>Error! : </strong>@errorMessage
            <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    
    <div>
        <button type="button" id="Add" data-toggle="modal" data-url='@Url.Action("mpcreate")' data-target="#addCustomerPrdouct" class="btn btn-primary">Add Customer</button>
    </div>
    <table class="table table-responsive table-hover" id="CustomerProductTable">
        <thead>
            <tr>
                <th>id</th>
                <th>CustomerId</th>
                <th>ProductId</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var customerP in Model)
                {
                    <tr>
                        <td>@customerP.Id</td>
                        <td>@customerP.CustomerId</td>
                        <td>@customerP.ProductId</td>
                        <td>
                            <form>
                               <div class="btn-group btn-group-sm">
                                <button asp-action="Details" asp-controller="CustomerProduct" asp-route-id="@customerP.Id" class="btn btn-primary">Details</button>


                                </div>
                                <div class="btn-group btn-group-sm">
                                    <button asp-action="Edit" asp-controller="CustomerProduct" asp-route-id="@customerP.Id" class="btn btn-primary">Edit</button>


                                </div>
                                
                                <div class="btn-group btn-group-sm">
                                    <button asp-action="Delete" asp-controller="CustomerProduct" asp-route-id="@customerP.Id" class="btn btn-danger">Delete</button>
                                </div>
                            </form>
                            <div class="btn-group btn-group-sm">
                                <button type="button" id="Add" data-toggle="modal" data-url='@Url.Action("QuickEdit",@customerP.Id)' @*data-id="@customerP.Id"*@ data-target="#EditCustomerPrdouct" class="btn btn-primary">Quick edit</button>


                            </div>
                            <div>
                                <button type="button" id="Add" data-toggle="modal" data-url='@Url.Action($"QuickShow")' data-w="@customerP.Id" data-target="#ShowDetails" class="btn btn-primary">Quick show</button>


                            </div>
                        </td>
                    </tr>

                }
            }
            else
            {
                <tr>
                    <td colspan="4">
                        <div><p>No Customers Avaliable at the moment</p></div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div id="modalhere"></div>
    @await Html.PartialAsync("MPcreate",new CustomerProducts())
    @await Html.PartialAsync("QuickShow",new CustomerProductViewModel())
    @await Html.PartialAsync("QuickEdit",new CustomerProductViewModel())
  


    

Views/CustomerProduct/MPcreate.cshtml
@model store1.Models.CustomerProducts
@{
    Layout = null;
}
<head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    </head>
<div class="modal fade" id="addCustomerPrdouct" tabindex="-1" role="dialog" aria-labelledby="addCustomerProductLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">create product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>
            <div class="modal-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <form asp-action="CreateCustomerProduct" method="post">
                    <div class="mb-3">
                        <label class="form-label">Id</label>
                        <input type="text" class="form-control" asp-for="Id" />
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">CustomerId</label>
                        <input type="text" class="form-control" asp-for="CustomerId" />
                        <span asp-validation-for="CustomerId" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label class="control-label">ProductId</label>
                        <input type="text" class="form-control" asp-for="ProductId" />
                        <span asp-validation-for="ProductId" class="text-danger"></span>
                    </div>

                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Add Customer</button>
                        <button type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

Views/CustomerProduct/QuickEdit.cshtml
@model store1.Models.MViews.CustomerProductViewModel
@{
   
    ViewData["Title"] = "Edit Customer product";
    var errorMessage = TempData["errorMessage"]?.ToString();
    var successMessage = TempData["successmessage"]?.ToString();
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
</head>
@if (!string.IsNullOrWhiteSpace(errorMessage))
{
    <div class="alert alert-danger">
        <strong>Error! : </strong>@errorMessage
        <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div class="modal fade" id="EditCustomerPrdouct" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Customer product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>
            <div class="modal-body">
        <form asp-action="UpdateProduct" method="post">

    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="Id" readonly />

    </div>
    <div class="mb-3">
        <label class="form-label">CustomerId</label>
        <input type="text" class="form-control" asp-for="CustomerId" value="@Model.CustomerId" />
        <span asp-validation-for="CustomerId" class="text-danger"></span>

    </div>
    <div class="mb-3">
        <label class="form-label">ProductId</label>
      <input type="text" class="form-control" asp-for="ProductId" value="@Model.ProductId" />
        <span asp-validation-for="ProductId" class="text-danger"></span>

    </div>

    <div class="d-grid">
        <button type="submit" class="btn btn-success">Update</button>
    </div>
</form>
            </div>
        </div>
    </div>
</div>

</html>
@section scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

<script>
   

</script>

Views/CustomerProduct/QuickShow.cshtml
@model store1.Models.MViews.CustomerProductViewModel

@Model List<CustomerProductModel>


    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Details</title>
        <style>
            tr {
                margin: 5px
            }
        </style>
    </head>
    <body>
        <div class="modal fade" id="ShowDetails" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">create product</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>

                    </div>
                    <div class="modal-body">
@*        @if (Model != null && Model.Customer.type == "Top")
        {
            <h3 class="h-25">Customer Name</h3>
            <p class="p-1">@Html.DisplayFor(modelitem=>Model.Customer.Name)</p>
            <h3 class="h-25">Customer type</h3>
            <p>@Html.DisplayFor(modelitem=>Model.Customer.type)</p>





            <br />
            <table class="table table-responsive table-hover ">
                <tr>
                    <th>Product name</th>
                    <th>Product Sale price</th>
                </tr>
                <tr>
*@
                 @*   <td>@Html.DisplayFor(product=>Model.Product.Name)</td>
                    <td>@Html.DisplayFor(product=>Model.Product.wholesalePrice)</td>

                </tr>

            </table>
        }*@

        else
        {
            <h3 class="h-25">Customer Name</h3>
            <p class="p-1">@Html.DisplayFor(modelitem=>Model.Customer.Name)</p>
            <h3 class="h-25">Customer type</h3>
            <p>@Html.DisplayFor(modelitem=>Model.Customer.type)</p>
            <br />
            <table class="table table-responsive table-hover ">
                <tr>
                    <th>Product name</th>
                    <th>Product price</th>
                </tr>
                <tr>

                    <td>@Html.DisplayFor(product=>Model.Product.Name)</td>
                    <td>@Html.DisplayFor(product=>Model.Product.wholesalePrice)</td>

                </tr>

            </table>
        }
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

Views/CustomerProduct/Show.cshtml
@model store1.Models.MViews.ViewModel

@{
    Layout = "_Layout";
}
    <!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Show</title>
</head>
<body>
    <form >
        <button value="Top" class="btn btn-success" asp-controller="CustomerProduct" asp-action="ShowTopCustomer">Top Customers</button>
        <button value="Regular" class="btn btn-success" asp-controller="CustomerProduct" asp-action="ShowRegularCustomer">Regular Customers</button>
    </form>



</body>

</html>